<?php $adminUsers = $this->getAllAdminUsers() ?>
<?php $tags = $this->getAllTags() ?>
<div class="content-header">
    <table cellspacing="0">
        <tbody>
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-permissions-user">WFN / Tagger / Manage Tags</h3></td>
        </tr>
        </tbody>
    </table>
</div>
<div class="grid">
    <div class="hor-scroll">
        <table cellspacing="0" class="data">
            <thead>
            <tr class="headings">
                <th><span class="nobr">ID</span></th>
                <th><span class="nobr">Name</span></th>
                <th><span class="nobr">Assigned User</span></th>
                <th><span class="nobr">Created At</span></th>
                <th><span class="nobr"></span></th>
            </tr>
            </thead>
            <tbody>
                <tr class="even">
                    <td></td>
                    <td><input type="text" class="input-text" id="tag-new-name"></td>
                    <td>
                        <select class="select" id="tag-new-user-id" style="width: 100%">
                            <option value=""></option>
                            <?php foreach ($adminUsers as $user): ?>
                                <option value="<?php echo $user->getId() ?>"><?php echo $user->getFirstname() . ' ' . $user->getLastname() ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td></td>
                    <td>
                        <button class="scalable add js-create-tag-btn" type="button">
                            <span><span><span>Create</span></span></span>
                        </button>
                    </td>
                </tr>
                <?php $count = 0; foreach ($tags as $tag): $count++ ?>
                    <tr class="<?php echo ($count % 2 == 0) ? 'even ' : ''?>">
                        <td><?php echo $tag->getId() ?></td>
                        <td>
                            <input type="text" class="input-text" id="tag-<?php echo $tag->getId() ?>-name" value="<?php echo $tag->getName() ?>">
                        </td>
                        <td>
                            <select class="select" id="tag-<?php echo $tag->getId() ?>-user-id" style="width: 100%">
                                <option value=""></option>
                                <?php foreach ($adminUsers as $user): ?>
                                    <option
                                        value="<?php echo $user->getId() ?>"
                                        <?php echo ($tag->getUserId() == $user->getId()) ? ' selected' : '' ?>>
                                        <?php echo $user->getFirstname() . ' ' . $user->getLastname() ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td><?php echo $tag->getCreatedAt() ?></td>
                        <td>
                            <button type="button" class="scalable save js-update-tag-btn" data-tag-id="<?php echo $tag->getId() ?>">
                                <span><span><span>Update</span></span></span>
                            </button>
                            <button type="button" class="scalable delete js-delete-tag-btn" data-tag-id="<?php echo $tag->getId() ?>" data-tag-name="<?php echo $tag->getName() ?>">
                                <span><span><span>Delete</span></span></span>
                            </button>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>
<script>
(function($) {
    $(function() {
        var loader = $('#loading-mask');
        // Create tag
        $('body').on('click', '.js-create-tag-btn', function() {
            loader.show();
            $.post('<?php echo $this->getUrl('wfn_tagger/tags/create') ?>', {
                name: $('#tag-new-name').val(),
                user_id: $('#tag-new-user-id').val(),
                form_key: '<?php echo $this->getFormKey() ?>'
            }).always(function() {
                location.reload();
            });
        });

        // Update tag
        $('body').on('click', '.js-update-tag-btn', function() {
            loader.show();
            var tagId = $(this).data('tag-id');
            $.post('<?php echo $this->getUrl('wfn_tagger/tags/update', ['id' => '{id}']) ?>'.replace('{id}', tagId), {
                name: $('#tag-' + tagId + '-name').val(),
                user_id: $('#tag-' + tagId + '-user-id').val(),
                form_key: '<?php echo $this->getFormKey() ?>'
            }).always(function() {
                location.reload();
            });
        });

        // Delete tag
        $('body').on('click', '.js-delete-tag-btn', function() {
            var tagName = $(this).data('tag-name');
            if (!confirm('Delete tag "' + tagName + '"?')) {
                return;
            }
            loader.show();
            var tagId = $(this).data('tag-id');
            $.get('<?php echo $this->getUrl('wfn_tagger/tags/delete', ['id' => '{id}']) ?>'.replace('{id}', tagId))
                .always(function() {
                    location.reload();
                });
        });
    });
}(jQuery));
</script>
