<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-shipping-method">Tags</h4>
    </div>
    <fieldset>
        <div>
            <input
                type="text"
                id="tag-input"
                value="<?php echo implode(',', array_keys($this->assignedTags)) ?>">
        </div>
        <strong>Click to add previously used tags:</strong>
        <div id="tag-buttons">
            <?php foreach ($this->allTags as $tag): ?>
                <button
                    type="button"
                    class="scalable"
                    data-id="<?php echo $tag['id'] ?>"
                    data-name="<?php echo $tag['name'] ?>"><?php echo $tag['name'] ?></button>
            <?php endforeach; ?>
        </div>
    </fieldset>
</div>
<script type="text/javascript">
    (function($) {
        var tagInput = $('#tag-input').selectize({
            plugins: ['remove_button'],
            delimiter: ',',
            persist: false,
            valueField: 'id',
            labelField: 'name',
            searchField: 'name',
            options: <?php echo json_encode(array_values($this->assignedTags)) ?>,
            create: function(input) {
                alert(2);
                return {
                    id: input,
                    name: input
                }
            }
        });

        var tagInputSelectize = tagInput[0].selectize;

        $('#tag-buttons').on('click', 'button', function() {
            var tagId = $(this).data('id');
            var tagName = $(this).data('name');
            tagInputSelectize.addOption({id: tagId, name: tagName});
            tagInputSelectize.addItem(tagId);
        });
    }(jQuery));

</script>
